---
- name: obtain real package name
  set_fact: 
    dhcpd_package_name: "{{ dhcpd_package_name|default ( _dhcpd_package_name ) }}"

- debug: var=dhcpd_package_name

- name: install required package 
  openbsd_pkg: name={{ item }} state=present
  with_items: [ '{{ dhcpd_package_name }}' ]
